language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
install:
 - pip install -r requirements.txt
 - pip install -e .
 - pip install -r requirements-test.txt
script: py.test --cov=britney
after_success:
 - pip install coveralls
 - coveralls
