language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
install:
 - pip install -r requirements.txt --use-mirrors
 - pip install -e .
 - pip install coverage
script: coverage run -m unittest discover tests/
after_success:
 - pip install coveralls
 - coveralls
